apiVersion: apps/v1
kind: Deployment
metadata:
  name: django2-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django2-backend
  template:
    metadata:
      labels:
        app: django2-backend
    spec:
      containers:
      - name: django2-backend
        image: mohamedmass1245/domain_django:v1
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "103.174.10.194"
        - name: DB_NAME
          value: "Testing"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "y7L^q8t78"
---
apiVersion: v1
kind: Service
metadata:
  name: django2-backend-service
spec:
  selector:
    app: django2-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000         # Port inside the container (Django app)
      targetPort: 8000   # Target port on the container
      nodePort: 30001    # External port on the node
